GAPED_animal_concerns_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/A/
GAPED_human_concerns_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/H/
GAPED_neutral_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/N/
GAPED_positive_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/P/
GAPED_snakes_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/Sn/
GAPED_spiders_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/Sp/
additional_animal_concerns_images:
- A105.bmp
additional_human_concerns_images:
- H088.bmp
additional_neutral_images:
- N016.bmp
- N082.bmp
- N004.bmp
- N068.bmp
additional_positive_images:
- P104.bmp
- P010.bmp
- P036.bmp
- P017.bmp
additional_snake_images:
- Sn059.bmp
additional_spider_images:
- Sp117.bmp
buffer_stimuli_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/N/
catch_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/catch_images/
catch_stimuli_images_list:
- tiger_caricature.jpeg
- bird_caricature.jpeg
- smiling_shark.jpeg
- squirrel_holding_a_gun.jpeg
- camel_caricature.jpeg
catch_stimuli_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/catch_images/
cross_image_name: cross.jpg
cross_image_path: /home/prietoab/sussuarana/clientes/davi/imagens/cross/
selected_animal_concerns_images:
- A104.bmp
selected_buffer_stimuli_images:
- N083.bmp
- N077.bmp
selected_human_concerns_images:
- H058.bmp
selected_neutral_images:
- N080.bmp
- N105.bmp
- N067.bmp
- N031.bmp
selected_positive_images:
- P020.bmp
- P079.bmp
- P116.bmp
- P109.bmp
selected_snake_images:
- Sn069.bmp
selected_spider_images:
- Sp001.bmp
user_id: 1
user_random_seed: 1
