GAPED_animal_concerns_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/A/
GAPED_human_concerns_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/H/
GAPED_neutral_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/N/
GAPED_positive_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/P/
GAPED_snakes_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/Sn/
GAPED_spiders_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/Sp/
additional_animal_concerns_images:
- A098.bmp
additional_human_concerns_images:
- H066.bmp
additional_neutral_images:
- N013.bmp
- N071.bmp
- N095.bmp
- N032.bmp
additional_positive_images:
- P039.bmp
- P118.bmp
- P042.bmp
- P102.bmp
additional_snake_images:
- Sn031.bmp
additional_spider_images:
- Sp032.bmp
buffer_stimuli_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/N/
catch_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/catch_images/
catch_stimuli_images_list:
- tiger_caricature.jpeg
- bird_caricature.jpeg
- smiling_shark.jpeg
- camel_caricature.jpeg
- squirrel_holding_a_gun.jpeg
catch_stimuli_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/catch_images/
cross_image_name: cross.jpg
cross_image_path: /home/prietoab/sussuarana/clientes/davi/imagens/cross/
selected_animal_concerns_images:
- A129.bmp
selected_buffer_stimuli_images:
- N086.bmp
- N102.bmp
selected_human_concerns_images:
- H090.bmp
selected_neutral_images:
- N076.bmp
- N090.bmp
- N044.bmp
- N083.bmp
selected_positive_images:
- P043.bmp
- P040.bmp
- P003.bmp
- P069.bmp
selected_snake_images:
- Sn008.bmp
selected_spider_images:
- Sp002.bmp
user_id: 444
user_random_seed: 444
